#!/usr/bin/env python3
"""Generate or verify the project-scoped paper translation agent config."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

from safe_atomic_io import atomic_write_text, validate_nonempty_text


GENERATOR_VERSION = "paper-translation-agent-v5-windows-resume-1"
DEFAULT_MODEL = "gpt-5.6-terra"
DEFAULT_REASONING_EFFORT = "high"
PACKET_CONSTRAINTS_VERSION = "paper-bilingual-body-reference-title-suffix-v5"
TRANSPORT_CONSTRAINTS_VERSION = "paper-translation-transport-compact-v3"


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def read_fragment(path: Path) -> str:
    fragment = path.read_text(encoding="utf-8").strip()
    if not fragment or "Translate every effective claim" not in fragment:
        raise ValueError("translation prompt fragment is empty or missing its fidelity rule")
    if "'''" in fragment:
        raise ValueError("translation prompt fragment cannot contain TOML triple-single-quotes")
    return fragment


def render_agent(fragment: str, *, model: str, reasoning_effort: str) -> tuple[str, str, str]:
    prompt_sha256 = sha256_text(fragment)
    developer_instructions = f"""You are the dedicated translation worker for bilingual Obsidian paper cards.

Read only the assignment manifest named by the parent task and the JSONL packet referenced by that manifest. The compact packet uses exactly three row forms: body `{{"id":"u...","type":"body","text":"..."}}`; deterministic title `{{"id":"r...","type":"reference_title","title":"..."}}`; ambiguous title `{{"id":"r...","type":"reference_title","entry":"..."}}`. Do not read the complete Markdown note, unrelated files, other skills, or the parent thread history. Do not use shell commands or patch tools to write files; the deterministic runner writes the validated output JSONL.

For every ordinary body unit, prepare exactly one object in `translations`: {{"unit_id":"u...","zh":"..."}}. For every `reference_title` unit, prepare exactly one object in `reference_titles`: {{"unit_id":"r...","source_title":"exact source substring","zh":"Chinese title only"}}. Preserve input order within each array. Emit no Markdown, analysis, headings, summaries, progress prose, or commentary.

{fragment}

If the complete assignment cannot be translated faithfully, do not claim completion. On success, report using the literal status `completed`; the final task response must be exactly one JSON object matching the runner-provided schema, with no surrounding prose: {{"status":"completed","translated_units":N,"translations":[{{"unit_id":"u00001","zh":"..."}}],"reference_titles":[{{"unit_id":"r00001","source_title":"...","zh":"..."}}]}}. Set N to the exact `unit_count` in the assignment manifest; it counts all pending body and reference-title units and nothing else. The runner validates this object, writes the declared JSONL output atomically, and emits the external compact path/hash status.
"""
    translator_fingerprint = sha256_text(
        "\0".join(
            (
                model,
                reasoning_effort,
                prompt_sha256,
                PACKET_CONSTRAINTS_VERSION,
                TRANSPORT_CONSTRAINTS_VERSION,
            )
        )
    )
    rendered = f'''# Generated by sync_paper_translation_agent_prompt.py; do not edit the prompt by hand.
# generator_version = "{GENERATOR_VERSION}"
# packet_constraints_version = "{PACKET_CONSTRAINTS_VERSION}"
# transport_constraints_version = "{TRANSPORT_CONSTRAINTS_VERSION}"
# prompt_sha256 = "{prompt_sha256}"
# translator_fingerprint = "{translator_fingerprint}"

name = "paper-translation-worker"
description = "Translate frozen academic-paper JSONL units and reference titles into faithful Chinese while preserving protected tokens."
model = "{model}"
model_reasoning_effort = "{reasoning_effort}"
sandbox_mode = "workspace-write"

developer_instructions = \'\'\'
{developer_instructions.rstrip()}
\'\'\'
'''
    return rendered, prompt_sha256, translator_fingerprint


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--agent-path", required=True)
    parser.add_argument(
        "--fragment-path",
        default=str(Path(__file__).resolve().parents[1] / "references" / "paper-translation-prompt-fragment.md"),
    )
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--reasoning-effort", default=DEFAULT_REASONING_EFFORT)
    args = parser.parse_args()

    fragment_path = Path(args.fragment_path).resolve()
    agent_path = Path(args.agent_path).resolve()
    fragment = read_fragment(fragment_path)
    rendered, prompt_sha256, translator_fingerprint = render_agent(
        fragment, model=args.model, reasoning_effort=args.reasoning_effort
    )
    if args.write:
        agent_path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(agent_path, rendered, validator=validate_nonempty_text)
        status = "written"
        ok = True
    else:
        actual = agent_path.read_text(encoding="utf-8") if agent_path.is_file() else ""
        ok = actual == rendered
        status = "synchronized" if ok else "stale"
    print(
        json.dumps(
            {
                "ok": ok,
                "status": status,
                "agent_path": str(agent_path),
                "prompt_sha256": prompt_sha256,
                "translator_fingerprint": translator_fingerprint,
            },
            ensure_ascii=False,
        )
    )
    return 0 if ok else 2


if __name__ == "__main__":
    raise SystemExit(main())
